version: 2
jobs:
  build:
    docker:
      # Pick a base image which matches the version of Node you need for
      # building from https://hub.docker.com/r/circleci/node/tags/
      #
      # Note: If using a different container, make sure it contains at least
      # git 2.6.0. (Use -stretch for circleci/node containers.)
      - image: circleci/node:6.11-stretch

    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      # - run: npm run build
      - deploy:
          command: .circleci/deploy.sh
